version: '3.2'
services:
  hatify:
    image: hugosandelius/hatify
    restart: always
    volumes:
      - static:/static
  tagga:
    image: hugosandelius/tagga
    restart: always
  nginx: 
    image: hugosandelius/nginx 
    restart: always
    ports: 
      - "80:80"
    volumes:
      - static:/static
volumes:
  static: