version: '3.2'
services:
  hatify:
    image: hugosandelius/hatify
    restart: unless-stopped
    volumes:
      - static:/static
  tagga:
    image: hugosandelius/tagga
    restart: unless-stopped
  leet:
    image: hugosandelius/1337
    environment:
      - SLACK_API_TOKEN
    volumes:
      - leetcache:/cache
    restart: unless-stopped
  nginx: 
    image: hugosandelius/nginx 
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - static:/static
volumes:
  static:
  leetcache: