version: '3.2'
services:
  hatify:
    build: 
      context: hatify
      cache_from:
        - hugosandelius/hatify
  tagga:
    build: 
      context: tagga
      cache_from:
        - hugosandelius/tagga
  leet:
    build:
      context: '1337'
      cache_from:
        - hugosandelius/1337
  nginx:  
    build: 
      context: nginx
      cache_from:
        - hugosandelius/nginx