version: '3.2'
services:
  hatify:
    image: hugosandelius/hatify
    restart: unless-stopped
    environment:
      - SEARCH_API_KEY
      - SEARCH_API_ENGINE_ID
      - SLACK_API_EMOJIFY_TOKEN
    volumes:
      - static:/static
  tagga:
    image: hugosandelius/tagga
    restart: unless-stopped
  leet:
    image: hugosandelius/1337
    environment:
      - SLACK_API_TOKEN
    volumes:
      - leetcache:/cache
    restart: unless-stopped
  nginx: 
    image: hugosandelius/nginx 
    restart: unless-stopped
    ports: 
      - "80:80"
    volumes:
      - static:/static
  portainer:
    image: portainer/portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  static:
  leetcache:
  portainer_data: