version: '2'
services:
  hatify:
    image: hugosandelius/hugosandelius.se:hatify
    build: ../hatify
    restart: always
    volumes:
      - /var/static:/static
  tagga:
    image: hugosandelius/hugosandelius.se:tagga
    build: ../tagga
    restart: always
  nginx: 
    image: hugosandelius/hugosandelius.se:nginx 
    build: nginx
    restart: always
    volumes:
      - /var/static:/static
    ports:
      - "80:80"