version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: |
            docker login -u hugosandelius -p $DOCKERHUB_PASSWD
            docker-compose pull
            docker-compose build
            docker-compose push
      - run:
          name: Deploy
          command: ./deploy.sh