version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Build
          command: |
            docker login -u hugosandelius -p $DOCKERHUB_PASSWD
            docker-compose pull
            docker-compose build
            docker-compose push
      - add_ssh_keys:
          fingerprints:
            - "a1:0e:d7:ed:fd:50:75:c5:52:d7:06:21:bd:d2:f2:e8"
      - run:
          name: Deploy
          command: ./deploy.sh